name: foo
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - gcc_linux-64
  - curl
  - zlib
  - numpy
  - pytest
  - pyBigWig
  - pip
  - pip:
    - certifi
    - charset-normalizer
    - contourpy
    - cycler
    - fonttools
    - idna
    - kiwisolver
    - matplotlib
    - packaging
    - pandas
    - pillow
    - pyparsing
    - python-dateutil
    - pytz
    - requests
    - six
    - tzdata
    - urllib3
