name: foo
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - gcc_linux-64
  - curl
  - zlib
  - numpy
  - pytest
  - pyBigWig
  - pip
  - pip:
    - certifi==2024.7.4
    - charset-normalizer==3.3.2
    - contourpy==1.2.1
    - cycler==0.12.1
    - fonttools==4.53.1
    - idna==3.7
    - kiwisolver==1.4.5
    - matplotlib==3.9.0
    - packaging==24.1
    - pandas==2.2.2
    - pillow==10.4.0
    - pyparsing==3.1.2
    - python-dateutil==2.9.0.post0
    - pytz==2024.1
    - requests==2.32.3
    - six==1.16.0
    - tzdata==2024.1
    - urllib3==2.2.2
